global using System.ComponentModel;
global using Microsoft.Office.Interop.Word;
global using System.IO;
global using System.Threading;
global using System.Windows;
global using Техописание_запчастей.Model;
global using Техописание_запчастей.View;
global using Microsoft.EntityFrameworkCore;
global using System.Configuration;
global using System;
global using System.Collections.Generic;
global using System.Windows.Input;
global using System.Linq;
global using sys = System.Windows.Controls;
global using wordApp = Microsoft.Office.Interop.Word;
global using Validator = Техописание_запчастей.Model.Validator;
global using System.Collections.ObjectModel;
global using System.Runtime.CompilerServices;