global using System.ComponentModel;
global using Техописание_запчастей.Model;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using System.Configuration;
global using System;
global using System.Collections.Generic;
global using System.Windows.Input;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Windows.Controls;
global using System.Collections;
global using Техописание_запчастей.View;
global using wordApp = Microsoft.Office.Interop.Word;
global using System.Text.RegularExpressions;
global using Validator = Техописание_запчастей.Model.Validator;